# fly.toml app configuration file generated for twitch-watcher on 2024-04-26T23:59:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twitch-watcher'
primary_region = 'fra'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
